INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (1, 'Lucifer', '2016-01-25', 0, '/contentFiles/imgs/series/lucifer.jpg', 'Fox');
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (2, 'The FLash', '2014-10-07', 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (3, 'Arrow', '2012-10-10', 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (4, 'Legends of Tomorrow', null, 1, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (5, 'The Gifted', null, 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (6, 'Marvel''s Spider-Man', null, 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (7, 'Doctor Who', null, 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (8, 'Man at Arms: Art of War', null, 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (9, 'The Big Bang Theory', null, 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (10, 'Mr.Robot', null, 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (11, 'Gotham', null, 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (12, 'Young Sheldon', null, 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (13, 'Digimon Adventures Tri 6', null, 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (14, 'Freedom Fighters: The Ray', null, 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (15, 'American Gods', null, 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (16, 'Krypton ', null, 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (17, 'Legion', null, 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (18, 'Patrick Melrose', null, 0, null, null);
INSERT INTO date_releases.series (id, name, date_started, ended, imageUrl, channel) VALUES (19, 'Young Justice', null, 0, null, null);
INSERT INTO date_releases.series_episodes (series_episodes_id, series_id, season, episode, release_date, notes) VALUES (266, 1, 1, 1, '2017-12-31', 'Test, zxcvabc, sdgasd');
INSERT INTO date_releases.users (id, user_name, password, img_url, first_name, middle_name, last_name, email) VALUES (1, 'PR', 'test123', null, '', '', '', 'p.ressos@hotmail.com');
INSERT INTO date_releases.users (id, user_name, password, img_url, first_name, middle_name, last_name, email) VALUES (2, 'PanRes', 'test123', null, null, null, null, 'panres13@gmail.com');