UPDATE test_db.series SET name = 'Lucifer', date_started = '2016-01-25', ended = 0, imageUrl = '/contentFiles/imgs/series/lucifer.jpg', channel = 'Fox' WHERE series_id = 1;
UPDATE test_db.series SET name = 'The FLash', date_started = '2014-10-07', ended = 0, imageUrl = '/contentFiles/imgs/series/2_The_Flash_Intertitle.png', channel = null WHERE series_id = 2;
UPDATE test_db.series SET name = 'Arrow', date_started = '2012-10-10', ended = 0, imageUrl = null, channel = null WHERE series_id = 3;
UPDATE test_db.series SET name = 'Legends of Tomorrow', date_started = null, ended = 1, imageUrl = null, channel = null WHERE series_id = 4;
UPDATE test_db.series SET name = 'The Gifted', date_started = null, ended = 0, imageUrl = null, channel = null WHERE series_id = 5;
UPDATE test_db.series SET name = 'Marvel''s Spider-Man', date_started = null, ended = 0, imageUrl = null, channel = null WHERE series_id = 6;
UPDATE test_db.series SET name = 'Doctor Who', date_started = null, ended = 0, imageUrl = null, channel = null WHERE series_id = 7;
UPDATE test_db.series SET name = 'Man at Arms: Art of War', date_started = null, ended = 0, imageUrl = null, channel = null WHERE series_id = 8;
UPDATE test_db.series SET name = 'The Big Bang Theory', date_started = null, ended = 0, imageUrl = null, channel = null WHERE series_id = 9;
UPDATE test_db.series SET name = 'Mr.Robot', date_started = null, ended = 0, imageUrl = null, channel = null WHERE series_id = 10;
UPDATE test_db.series SET name = 'Gotham', date_started = null, ended = 0, imageUrl = null, channel = null WHERE series_id = 11;
UPDATE test_db.series SET name = 'Young Sheldon', date_started = null, ended = 0, imageUrl = null, channel = null WHERE series_id = 12;
UPDATE test_db.series SET name = 'Digimon Adventures Tri 6', date_started = null, ended = 0, imageUrl = null, channel = null WHERE series_id = 13;
UPDATE test_db.series SET name = 'Freedom Fighters: The Ray', date_started = null, ended = 0, imageUrl = null, channel = null WHERE series_id = 14;
UPDATE test_db.series SET name = 'American Gods', date_started = null, ended = 0, imageUrl = null, channel = null WHERE series_id = 15;
UPDATE test_db.series SET name = 'Krypton ', date_started = null, ended = 0, imageUrl = null, channel = null WHERE series_id = 16;
UPDATE test_db.series SET name = 'Legion', date_started = null, ended = 0, imageUrl = null, channel = null WHERE series_id = 17;
UPDATE test_db.series SET name = 'Patrick Melrose', date_started = null, ended = 0, imageUrl = null, channel = null WHERE series_id = 18;
UPDATE test_db.series SET name = 'Young Justice', date_started = null, ended = 0, imageUrl = null, channel = null WHERE series_id = 19;